// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"github.com/google/uuid"
)

type Order struct {
	OrderID       uuid.UUID
	OrderQuantity int32
}

type OrderPack struct {
	OrderPacksID uuid.UUID
	OrderID      uuid.UUID
	PackSize     int32
	PackQuantity int32
}

type Pack struct {
	PackSize int32
}
