// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddOrder(ctx context.Context, arg AddOrderParams) error
	AddOrderPack(ctx context.Context, arg AddOrderPackParams) error
	AddPack(ctx context.Context, packSize int32) error
	RemovePackBySize(ctx context.Context, packSize int32) error
	RetrieveOrderById(ctx context.Context, orderID uuid.UUID) (Order, error)
	RetrieveOrderPacksByOrder(ctx context.Context, orderID uuid.UUID) ([]RetrieveOrderPacksByOrderRow, error)
	RetrieveOrders(ctx context.Context) ([]Order, error)
	RetrievePacks(ctx context.Context) ([]int32, error)
}

var _ Querier = (*Queries)(nil)
